### PR TITLE
fix: reduce dagPb and dagCbor handler complexity

### LINKED ISSUE #43: chore: reduce line complexity in `handleDagPb` and `handleDagCbor`
https://github.com/ipfs/helia-verified-fetch/pull/39#discussion_r1556124242

We need to break out some of the common functionality

### PR DESCRIPTION
**Pull request by SgtPooki**
## Title

fix: reduce dagPb and dagCbor handler complexity

## Description

fixes #43

- create and use `setIpfsRoots` function
- pull out walkPath logic into separate function

## Notes & open questions

I'm not 100% sure about how to handle the `isObjectNode === false` case.

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/verified-fetch/src/verified-fetch.ts [hunk 1]
```diff
@@ -259,7 +252,27 @@ export class VerifiedFetch {
...
+    if (pathDetails instanceof Response) {
+      return pathDetails
+    }
+    const ipfsRoots = pathDetails.ipfsRoots
+    if (isObjectNode(pathDetails.terminalElement)) {
+      terminalElement = pathDetails.terminalElement
+    } else {
+      // this should never happen, but if it does, we should log it and return notSupportedResponse
+      this.log.error('terminal element is not a dag-cbor node')
+      return notSupportedResponse(resource, 'Terminal element is not a dag-cbor node')
```
Comment (SgtPooki) [inline packages/verified-fetch/src/verified-fetch.ts:272]: not sure if this is the right thing to do here, or if we want to allow walking the path to fail and still query `helia.blockstore.get(cid, options)`

File: packages/verified-fetch/src/verified-fetch.ts [hunk 2]
```diff
@@ -299,35 +312,23 @@ export class VerifiedFetch {
...
-      return badGatewayResponse(resource.toString(), 'Error walking path')
+    const pathDetails = await this.handlePathWalking({ cid, path, resource, options })
+    if (pathDetails instanceof Response) {
+      return pathDetails
     }
+    const ipfsRoots = pathDetails.ipfsRoots
+    const terminalElement = pathDetails.terminalElement
 
-    let resolvedCID = terminalElement?.cid ?? cid
+    let resolvedCID = terminalElement.cid
```
Comment (SgtPooki) [inline packages/verified-fetch/src/verified-fetch.ts:331]: do we want to keep the fallback to root CID? we shouldn't need to, but I could use a second set of eyes

**Review by SgtPooki — COMMENTED** [review]
self review

File: packages/verified-fetch/src/types.ts [hunk 3]
```diff
@@ -1,3 +1,32 @@
+import { type AbortOptions } from '@libp2p/interface'
+import { type CID } from 'multiformats/cid'
+import type { VerifiedFetchInit } from './index.js'
+
 export type RequestFormatShorthand = 'raw' | 'car' | 'tar' | 'ipns-record' | 'dag-json' | 'dag-cbor' | 'json' | 'cbor'
 
 export type SupportedBodyTypes = string | ArrayBuffer | Blob | ReadableStream<Uint8Array> | null
+
+export interface FetchHandlerFunctionArg {
```
Comment (SgtPooki) [inline packages/verified-fetch/src/types.ts:9]: note: cacheKey was removed

File: packages/verified-fetch/src/utils/walk-path.ts [hunk 4]
```diff
@@ -37,3 +40,23 @@ export async function walkPath (blockstore: ReadableStorage, path: string, optio
...
   return node.type === 'object'
 }
+
+/**
+ * Attempts to walk the path in the blockstore, returning ipfsRoots needed to resolve the path, and the terminal element.
+ * If the signal is aborted, the function will throw an AbortError
+ * If a terminal element is not found, a notFoundResponse is returned
+ * If another unknown error occurs, a badGatewayResponse is returned
+ */
+export async function handlePathWalking ({ cid, path, resource, options, blockstore, log }: Omit<FetchHandlerFunctionArg, 'session'> & { blockstore: Blockstore, log: Logger }): Promise<PathWalkerResponse | Response> {
```
Comment (SgtPooki) [inline packages/verified-fetch/src/utils/walk-path.ts:50]: this was moved to `walk-path.ts` from `verified-fetch.ts` because that file is getting much too large

File: packages/verified-fetch/src/verified-fetch.ts [hunk 5]
```diff
@@ -156,7 +126,8 @@ export class VerifiedFetch {
     this.log.trace('created VerifiedFetch instance')
   }
 
-  private getBlockstore (root: CID, key: string, useSession: boolean, options?: AbortOptions): Blockstore {
+  private getBlockstore (root: CID, resource: string | CID, useSession: boolean, options?: AbortOptions): Blockstore {
+    const key = resourceToSessionCacheKey(resource)
```
Comment (SgtPooki) [inline packages/verified-fetch/src/verified-fetch.ts:130]: instead of constructing the key in `fetch` function, construct in here and just use the resource that `FetchHandlerFunctionArg` already has.

**Review by SgtPooki — COMMENTED** [review]
self review
