### PR TITLE
fix: missing paths returns 404 instead of 502

### LINKED ISSUE #53: Missing paths should 404
When requesting paths that don't exist, the `Response` is returned as a 502, we should check for the `ERR_NOT_FOUND` `.code` property and translate that into a 404.

```
  helia:verified-fetch:error error walking path icons/favicon-16x16.png Error: file does not exist
    at unixFsResolver (file:///Users/alex/Documents/Workspaces/ipfs/helia-http-gateway-sessions/node_modules/ipfs-unixfs-exporter/dist/src/resolvers/unixfs-v1/index.js:56:27)
    at async walkPath (file:///Users/alex/Documents/Workspaces/ipfs/helia-http-gateway-sessions/node_modules/ipfs-unixfs-exporter/dist/src/index.js:107:24)
    at async walkPath (file:///Users/alex/Documents/Workspaces/ipfs/helia-http-gateway-sessions/node_modules/@helia/verified-fetch/dist/src/utils/walk-path.js:6:22)
    at async VerifiedFetch.handleDagPb (file:///Users/alex/Documents/Workspaces/ipfs/helia-http-gateway-sessions/node_modules/@helia/verified-fetch/dist/src/verified-fetch.js:271:33)
    at async VerifiedFetch.fetch (file:///Users/alex/Documents/Workspaces/ipfs/helia-http-gateway-sessions/node_modules/@helia/verified-fetch/dist/src/verified-fetch.js:495:24)
    at async fetch (file:///Users/alex/Documents/Workspaces/ipfs/helia-http-gateway-sessions/dist/src/helia-http-gateway.js:68:22)
    at async Object.handler (file:///Users/alex/Documents/Workspaces/ipfs/helia-http-gateway-sessions/dist/src/helia-http-gateway.js:144:21) {
  code: 'ERR_NOT_FOUND'
} +10ms
```

It may just need adding to this array:

https://github.com/ipfs/helia-verified-fetch/blob/f5299cf60c6e964d1b86d50a947812c9d7d18279/packages/verified-fetch/src/verified-fetch.ts#L322

### PR DESCRIPTION
**Pull request by 2color**
Fixes #53

## Notes

When initially writing the test for this, I discovered a bug when trying to create a dag-pb CID, reported as https://github.com/ipfs/helia/issues/506

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by SgtPooki — APPROVED** [review]

File: packages/verified-fetch/src/verified-fetch.ts [hunk 1]
```diff
@@ -316,7 +316,7 @@ export class VerifiedFetch {
       terminalElement = pathDetails.terminalElement
     } catch (err: any) {
       options?.signal?.throwIfAborted()
-      if (['ERR_NO_PROP', 'ERR_NO_TERMINAL_ELEMENT'].includes(err.code)) {
+      if (['ERR_NO_PROP', 'ERR_NO_TERMINAL_ELEMENT', 'ERR_NOT_FOUND'].includes(err.code)) {
         return notFoundResponse(resource.toString())
```
Comment (SgtPooki) [inline packages/verified-fetch/src/verified-fetch.ts:320]: I wonder if we should default to notFoundResponse and only return badGatewayResponse for specific scenarios.

**Review by SgtPooki — APPROVED** [review]
comments
