### PR TITLE
fix: aborted signals throw libp2p AbortError

### LINKED ISSUE #25: Abort signal is not respected
When passing an `new AbortController().signal` to a verifiedFetch request, aborting does not seem to work. 

You can see this in action in the reproduction, where if you click to fetch IPNS and right after click Abort Fetch, the `controller.abort()` call does not cause the promise from the `verifiedFetch` call to throw an error as [you'd expect in `Fetch`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController#examples)

To make this easier to test, I've added a reproduction:

[Reproduction](https://codesandbox.io/p/sandbox/heali-verified-fetch-example-m5zmfd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltygflrv00073b6iog3r7al4%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltygflrv00033b6iccj4x99g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltygflrv00043b6ivjdppdjn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltygflrv00063b6i2wmmuv2t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltygflrv00033b6iccj4x99g%2522%253A%257B%2522id%2522%253A%2522cltygflrv00033b6iccj4x99g%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltygflrv00063b6i2wmmuv2t%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltygflrv00053b6if14t6jmc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltygflrv00063b6i2wmmuv2t%2522%252C%2522activeTabId%2522%253A%2522cltygflrv00053b6if14t6jmc%2522%257D%252C%2522cltygflrv00043b6ivjdppdjn%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltygflrv00043b6ivjdppdjn%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### PR DESCRIPTION
**Pull request by SgtPooki**
## Title

fix: aborted signals throw libp2p AbortError

## Description

Fixes #25, specifically https://github.com/ipfs/helia-verified-fetch/issues/25#issuecomment-2014852934

### Summary of changes:

* signal aborts throw `AbortError` from `@libp2p/interface` instead of returning a Response object
    * Updated README.md to mention that this AbortError is not the typical DOMException AbortError thrown by native `fetch`
* updated the URL for not implemented codec requests to point to the correct repo
* added tests to ensure that aborts during `.stat` and `.cat` are handled correctly

## Notes & open questions

N/A

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/verified-fetch/src/verified-fetch.ts [hunk 1]
```diff
@@ -454,6 +460,7 @@ export class VerifiedFetch {
    * TODO: move operations called by fetch to a queue of operations where we can
    * always exit early (and cleanly) if a given signal is aborted
    */
+  // eslint-disable-next-line complexity
```
Comment (SgtPooki) [inline packages/verified-fetch/src/verified-fetch.ts:463]: the additional `if (options?.signal?.aborted === true) {` required adding this.

File: packages/verified-fetch/test/abort-handling.spec.ts [hunk 2]
```diff
@@ -62,6 +72,29 @@ describe('abort-handling', function () {
...
+      return {
+        cid,
+        type: 'file',
+        fileSize: BigInt(0),
+        dagSize: BigInt(0),
+        blocks: 1,
+        localFileSize: BigInt(0),
+        localDagSize: BigInt(0)
+      }
+    })
```
Comment (SgtPooki) [inline packages/verified-fetch/test/abort-handling.spec.ts:97]: defaults that timeout.... override with new `.callsFake` if you want it to return something valid.

**Review by SgtPooki — COMMENTED** [review]
self review
