### PR TITLE
fix: etag is path aware

### LINKED ISSUE #196: bug: etag not set correctly for paths
when requesting http://bafybeifiugn3zaj67dh6zqlgqpnzkbykbec3iur6wpb2zaz44ekcazyew4.ipfs.localhost:8345/image.jpeg, we should not be setting etag to `"bafybeifiugn3zaj67dh6zqlgqpnzkbykbec3iur6wpb2zaz44ekcazyew4"`, but we currently are.

### PR DESCRIPTION
**Pull request by SgtPooki**
## Title

fix: etag is path aware

## Description

Update plugin types & make work with `handleFinaleResponse`, clean up `fetch` impl internals, add get-e-tag test to verify path-awareness.

Fixes #196

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/verified-fetch/src/verified-fetch.ts [hunk 1]
```diff
@@ -199,7 +188,7 @@ export class VerifiedFetch {
     }
 
     if (cid != null && response.headers.get('etag') == null) {
-      response.headers.set('etag', getETag({ cid, reqFormat, weak: false }))
+      response.headers.set('etag', getETag({ cid: pathDetails?.terminalElement.cid ?? cid, reqFormat, weak: false }))
```
Comment (SgtPooki) [inline packages/verified-fetch/src/verified-fetch.ts:191]: this is the actual etag fix

**Review by SgtPooki — COMMENTED** [review]
self review

File: packages/verified-fetch/src/verified-fetch.ts (hunk 1 above)
Comment (Mkirby8867) [reply packages/verified-fetch/src/verified-fetch.ts:191]: This is confusing
